#!/usr/bin/env python3
"""Audit the am_fix.c front end gain tables on the host.

There is no emulator for the radio, but the gain-table code is plain C and can be
checked off-target. This pulls CreateTable() and the static lookup table straight
out of am_fix.c, wraps them in a harness, and verifies that:

  * every entry's reg_val decodes back to the gain_dB it claims,
  * both tables rise monotonically over entries 1..n-1,
  * no entry sets a bit above REG_13's defined <9:0> field,
  * sizeof(t_gain_table) is still 3.

Because it reads am_fix.c rather than a copy, it cannot drift from the source.

Usage:
    python3 utils/gain_table_audit.py            # generate + build + run
    python3 utils/gain_table_audit.py --emit     # just print the harness C

Build prerequisites (Debian/Ubuntu):
    sudo apt-get install -y build-essential gcc-arm-linux-gnueabihf qemu-user-static

The ARM run matters: arm-linux-gnueabihf is ARMv7-A rather than the radio's
ARMv6-M Cortex-M0, but it has the right data model and catches ABI-sensitive
bugs. It is what exposed the GainData union padding leak - at -O0 that target
returned 0x15 in REG_13 bits <15:10>, where x86-64 happened to return zero.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
AM_FIX = os.path.join(HERE, os.pardir, "am_fix.c")

HARNESS = r"""
/* generated by utils/gain_table_audit.py - do not edit */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#define ARRAY_SIZE(a) (sizeof(a)/sizeof((a)[0]))

typedef struct {
    uint16_t reg_val;
    int8_t   gain_dB;
} __attribute__((packed)) t_gain_table;

static const t_gain_table shipped[] =
{@@TABLE@@
};

t_gain_table gain_table[100] = {{0x03BE, -7}};
uint8_t gain_table_size = 0;

@@CREATE@@

/* the four front end stages, as REG_13 <9:8> <7:5> <4:3> <2:0> select them */
static const int8_t s_lna_short[] = {-28, -24, -19,  0};
static const int8_t s_lna[]       = {-24, -19, -14, -9, -6, -4, -2, 0};
static const int8_t s_mixer[]     = { -8,  -6,  -3,  0};
static const int8_t s_pga[]       = {-33, -27, -21, -15, -9, -6, -3, 0};

static int decode(uint16_t r)
{
    return s_lna_short[(r >> 8) & 3] + s_lna[(r >> 5) & 7]
         + s_mixer[(r >> 3) & 3] + s_pga[r & 7];
}

static int audit(const char *what, const t_gain_table *t, unsigned n)
{
    int bad = 0;

    for (unsigned i = 0; i < n; i++) {
        if (t[i].reg_val & ~0x03FFu) {
            printf("  %s[%2u] reg 0x%04X sets bits above <9:0> (padding leak)\n",
                   what, i, t[i].reg_val);
            bad = 1;
        }
        int d = decode(t[i].reg_val);
        if (d != t[i].gain_dB) {
            printf("  %s[%2u] reg 0x%04X claims %4ddB but decodes to %4ddB\n",
                   what, i, t[i].reg_val, t[i].gain_dB, d);
            bad = 1;
        }
    }

    /* entry 0 is the stock QS setting and sits outside the sorted run */
    for (unsigned i = 2; i < n; i++) {
        if (t[i].gain_dB <= t[i - 1].gain_dB) {
            printf("  %s not monotonic at %u: %ddB then %ddB\n",
                   what, i, t[i - 1].gain_dB, t[i].gain_dB);
            bad = 1;
        }
    }

    printf("  %-10s %2u entries : %s\n", what, n, bad ? "FAIL" : "ok");
    return bad;
}

int main(void)
{
    int bad = (sizeof(t_gain_table) != 3);
    if (bad)
        printf("  sizeof(t_gain_table) = %u, want 3\n",
               (unsigned)sizeof(t_gain_table));

    bad |= audit("shipped", shipped, ARRAY_SIZE(shipped));

    CreateTable();
    bad |= audit("generated", gain_table, gain_table_size);

    printf("%s\n", bad ? "FAIL" : "PASS");
    return bad;
}
"""


def build_harness():
    with open(AM_FIX, "rb") as fh:
        src = fh.read().decode("utf-8").replace("\r\n", "\n")

    start = src.index("void CreateTable()")
    create = src[start:src.index("\n#endif\n", start)]

    match = re.search(
        r"static const t_gain_table gain_table\[\] =\n\{(.*?)\n\};", src, re.S)
    if not match:
        sys.exit("could not find the static gain_table in am_fix.c")

    return HARNESS.replace("@@TABLE@@", match.group(1)).replace("@@CREATE@@", create)


def run(tmpdir, harness):
    path = os.path.join(tmpdir, "gain_table_audit.c")
    with open(path, "w", newline="\n") as fh:
        fh.write(harness)

    common = ["-std=c2x", "-Wall", "-Wextra"]
    targets = []

    if shutil.which("gcc"):
        for opt in ("-O0", "-O1", "-O2", "-Os"):
            targets.append(("x86-64 " + opt, ["gcc"] + common + [opt], []))
        targets.append(("x86-64 asan",
                        ["gcc"] + common + ["-O1", "-fsanitize=address,undefined"], []))

    if shutil.which("arm-linux-gnueabihf-gcc") and shutil.which("qemu-arm-static"):
        for opt in ("-O0", "-O1", "-O2", "-Os"):
            targets.append(("armhf  " + opt,
                            ["arm-linux-gnueabihf-gcc"] + common + [opt, "-static"],
                            ["qemu-arm-static"]))

    if not targets:
        sys.exit("no usable compiler found - see the prerequisites in this file's docstring")

    failures = 0
    for name, compile_cmd, runner in targets:
        exe = os.path.join(tmpdir, "audit")
        built = subprocess.run(compile_cmd + ["-o", exe, path],
                               capture_output=True, text=True)
        if built.returncode != 0:
            print("%-14s : BUILD FAILED\n%s" % (name, built.stderr.strip()))
            failures += 1
            continue

        got = subprocess.run(runner + [exe], capture_output=True, text=True)
        verdict = got.stdout.strip().splitlines()[-1] if got.stdout.strip() else "no output"
        print("%-14s : %s" % (name, verdict))
        if got.returncode != 0:
            failures += 1
            for line in got.stdout.splitlines()[:-1]:
                if line.strip():
                    print("               %s" % line.strip())

    return failures


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--emit", action="store_true",
                    help="print the generated harness instead of building it")
    args = ap.parse_args()

    harness = build_harness()

    if args.emit:
        sys.stdout.write(harness)
        return 0

    with tempfile.TemporaryDirectory() as tmpdir:
        return 1 if run(tmpdir, harness) else 0


if __name__ == "__main__":
    sys.exit(main())
